spring:
  application:
    name: feign-consumer
server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
      
feign:
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000